# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  siblings-only: true

# MD033/no-inline-html Inline HTML
MD033: false

# MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading
MD041: false
