name: Bug Report
description: File a bug report
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Before submitting a bug report, please make sure you have read this *entire* form, and that:
      * You have read the [PolyMC wiki](https://polymc.org/wiki/) and it has not answered your question.
      * Your bug is not caused by Minecraft or any mods you have installed.
      * Your issue has not been reported before, [make sure to use the search function!](https://github.com/PolyMC/PolyMC/issues)

      **Do not forget to give your issue a descriptive title.** "Bug in the instance screen" makes it hard to distinguish issues at a glance.
- type: dropdown
  attributes:
    label: Operating System
    description: If you know this bug occurs on multiple operating systems, select all you have tested.
    multiple: true
    options:
    - Windows
    - macOS
    - Linux
    - Other
- type: textarea
  attributes:
    label: Version of PollyMC
    description: The version of PollyMC used in the bug report.
    placeholder: PollyMC 1.4.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Description of bug
    description: What did you expect to happen, what happened, and why is it incorrect?
    placeholder: The parrot button should show a parrot, but it showed a cat instead!
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: A bulleted list, or an exported instance if relevant.
    placeholder: "* Press the parrot button"
  validations:
    required: true
- type: textarea
  attributes:
    label: Suspected cause
    description: If you know what could be causing this bug, describe it here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: This issue is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my bug.
      required: true
