name: Suggestion
description: Make a suggestion
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      ### Use this form to suggest a feature for PollyMC.
- type: input
  attributes:
    label: Role
    description: In what way do you use PollyMC that needs this feature?
    placeholder: I play modded Minecraft.
  validations:
    required: true
- type: input
  attributes:
    label: Suggestion
    description: What do you want PollyMC to do?
    placeholder: I want the parrot button to squawk.
  validations:
    required: true
- type: input
  attributes:
    label: Benefit
    description: Why do you need PollyMC to do this?
    placeholder: so that I can always hear a parrot when I need to.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: This suggestion is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
      required: true
- type: textarea
  attributes:
    label: You may use the editor below to elaborate further.
